config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :adventures, except: :destroy

    root 'adventures#index'

    get 'myadventures' => 'adventures#index'

end

app/models/adventure.rb
class Adventure < ActiveRecord::Base
	mount_uploader :picture, PictureUploader
	def expired? 
		visit < Date.today
	end

	validates_presence_of :name
	validates_numericality_of :cents
	has_many :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :adventure
  validates_presence_of :user_name, :email, :body, :adventure_id
  
end

app/controllers/adventures_controller.rb
class AdventuresController < ApplicationController
  before_action :set_adventure, only: [:show, :edit, :update, :destroy]

  # GET /adventures
  # GET /adventures.json
  def index
    if params[:order] 
        @adventures = Adventure.order(params[:order])
    else
        @adventures = Adventure.all
    end

    if params[:reverse] 
        @adventures = @adventures.reverse
    end

    if params[:free]
      @adventures = @adventures.where(cents: 0)
    end

    if params[:name]
      @adventures = @adventures.where name: params[:name]
    end

    if params[:filter]
      @adventures = @adventures.where "name LIKE '%#{params[:filter]}%'"
    end

  end

  # GET /adventures/1
  # GET /adventures/1.json
  def show
    @comments = @adventure.comments
    @comment = @adventure.comments.build
  end

  # GET /adventures/new
  def new
    @adventure = Adventure.new
  end

  # GET /adventures/1/edit
  def edit
  end

  # POST /adventures
  # POST /adventures.json
  def create
    @adventure = Adventure.new(adventure_params)

    respond_to do |format|
      if @adventure.save
        format.html { redirect_to @adventure, notice: 'Adventure was successfully created.' }
        format.json { render :show, status: :created, location: @adventure }
      else
        format.html { render :new }
        format.json { render json: @adventure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /adventures/1
  # PATCH/PUT /adventures/1.json
  def update
    respond_to do |format|
      if @adventure.update(adventure_params)
        format.html { redirect_to @adventure, notice: 'Adventure was successfully updated.' }
        format.json { render :show, status: :ok, location: @adventure }
      else
        format.html { render :edit }
        format.json { render json: @adventure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adventures/1
  # DELETE /adventures/1.json
  def destroy
    @adventure.destroy
    respond_to do |format|
      format.html { redirect_to adventures_url, notice: 'Adventure was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_adventure
      @adventure = Adventure.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def adventure_params
      params.require(:adventure).permit(:name, :description, :picture, :visit, :cents, :address, :website)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.adventure, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_name, :email, :body, :adventure_id)
    end
end

app/helpers/adventures_helper.rb
module AdventuresHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/adventures/_form.html.erb
<%= form_for @adventure, :html => {:multipart => true} do |f| %>
  <% if @adventure.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@adventure.errors.count, "error") %> prohibited this adventure from being saved:</h2>

      <ul>
      <% @adventure.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="field">
    <%= f.label :visit %><br>
    <%= f.date_select :visit %>
  </div>
  <div class="field">
    <%= f.label :cents %><br>
    <%= f.number_field :cents %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </div>
    <div class="field">
    <%= f.label :website%><br>
    <%= f.text_area :website %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/adventures/edit.html.erb
<h1>Editing Adventure</h1>

<%= render 'form' %>

<%= link_to 'Show', @adventure %> |
<%= link_to 'Back', adventures_path %>

app/views/adventures/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= pluralize(@adventures.count, 'adventure') %></h1>


<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Description</th>
      <th>Picture</th>
      <th>Visit</th>
      <th>Expired</th>
      <th>Cents: <a href="/adventures?order=cents&reverse=true">H-L</a></th>
      <th>Address</th>
      <th>Website</th>
      <th>Author</th>
      <th>Comments</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @adventures.each do |adventure| %>
      <tr>
        <td><%= adventure.id %></td>
        <td><%= link_to adventure.name, adventures_path(name: adventure.name) %></td>
        <td><%= adventure.description %></td>
        <td> <%= image_tag(adventure.picture_url, :width => 100) if adventure.picture.present? %></td>
        <td><%= adventure.visit %></td>
        <td><% if adventure.expired? %>
             X
            <% end %>
        </td>
        <td><% if adventure.cents == 0 %>
                Free
            <% else %>
              <%= number_to_currency(adventure.cents/100) %>
            <% end %>
        </td>
        <td><%= adventure.address %></td>
        <td><%= adventure.website %></td>
        <td> </td>
        <td><%= adventure.comments.count %></td>
        <td><%= link_to 'Show', adventure %></td>
        <td><%= link_to 'Edit', edit_adventure_path(adventure) %></td>
       <!-- <td><%= link_to 'Destroy', adventure, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Adventure', new_adventure_path %><br />
<a href="/adventures?order=cents">List by Price, Low to High</a><br />
<a href="/adventures?order=name">List by Name</a><br />
<a href="/adventures?order=description">List by Description</a><br />

app/views/adventures/new.html.erb
<h1>New Adventure</h1>

<%= render 'form' %>

<%= link_to 'Back', adventures_path %>

app/views/adventures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @adventure.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @adventure.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag(@adventure.picture_url, :width => 600) if @adventure.picture.present? %>
</p>

<p>
  <strong>Visit:</strong>
  <%= @adventure.visit %>
</p>

<p>
  <strong>Cents:</strong>
  <%= @adventure.cents %>
</p>

<p>
  <strong>Address:</strong>
  <%= @adventure.address %>
</p>

<p>
  <strong>Website:</strong>
  <%= @adventure.website %>
</p>

<h2> Comments</h2>


 <% @comments.each do |comment| %>
 <table width="30%"><tr><td># <%= comment.id %></td>
   <td> Name: <%= mail_to comment.email,  comment.user_name %><br />
    <p><%= comment.body %></p>
  </td>
</tr>
</table>
    <hr>
  <% end %>

<%= render 'comments/form' %>

<%= link_to 'Edit', edit_adventure_path(@adventure) %> |
<%= link_to 'Back', adventures_path %>

app/views/comments/_form.html.erb
<h1>New Comment</h1>

<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<%= f.hidden_field :adventure_id %>

  <div class="field">
    <%= f.label :user_name %><br>
    <%= f.text_field :user_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>User name</th>
      <th>Email</th>
      <th>Body</th>
      <th>Adventure</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user_name %></td>
        <td><%= comment.email %></td>
        <td><%= comment.body %></td>
        <td><%= comment.adventure %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User name:</strong>
  <%= @comment.user_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @comment.email %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Adventure:</strong>
  <%= @comment.adventure %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>

<%= yield %>

</body>
</html>